# Generated by Django 4.2.7 on 2023-11-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='in_stock/', verbose_name='Фото')),
                ('name', models.CharField(max_length=20, verbose_name='Наименование')),
                ('col', models.CharField(max_length=20, verbose_name='Количество')),
                ('price', models.CharField(max_length=15, verbose_name='Цена')),
                ('description', models.CharField(max_length=100, verbose_name='Описание')),
                ('date', models.DateField(verbose_name='Дата прибытия')),
            ],
        ),
    ]
