# Generated by Django 4.2.7 on 2023-11-09 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_item_delete_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='date',
            new_name='item_date',
        ),
    ]
