# Generated by Django 4.2.7 on 2023-11-09 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_rename_date_item_item_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='col',
            field=models.IntegerField(max_length=20, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(max_length=15, verbose_name='Цена'),
        ),
    ]
