# Generated by Django 4.2.7 on 2023-11-09 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_alter_item_col_alter_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='col',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
    ]
