# Generated by Django 4.2.7 on 2023-12-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_alter_item_col_alter_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(default=None, max_length=50, verbose_name='Категория'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='minimum',
            field=models.IntegerField(null=True, verbose_name='Минимальное количество'),
        ),
        migrations.AddField(
            model_name='item',
            name='mult',
            field=models.IntegerField(null=True, verbose_name='Кратность'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Наименование'),
        ),
    ]
