# Generated by Django 4.2.7 on 2023-12-12 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_item_image_id_alter_item_minimum_alter_item_mult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
