# Generated by Django 4.2.7 on 2023-12-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0008_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('photo', models.ImageField(upload_to='items/', verbose_name='Фото')),
                ('description', models.CharField(max_length=100, verbose_name='Описание')),
                ('category', models.CharField(max_length=50, verbose_name='Категория')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('col', models.IntegerField(verbose_name='Количество')),
                ('mult', models.IntegerField(blank=True, null=True, verbose_name='Кратность')),
                ('minimum', models.IntegerField(blank=True, null=True, verbose_name='Минимальное количество')),
                ('item_date', models.DateField(verbose_name='Дата прибытия')),
                ('image_id', models.TextField(blank=True, null=True, verbose_name='image ID')),
            ],
        ),
    ]
