# Generated by Django 4.2.7 on 2024-01-18 09:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0015_excelinput_alter_instock_photo_alter_item_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelinput',
            name='excel_file',
            field=models.FileField(upload_to='excel/', validators=[django.core.validators.FileExtensionValidator(['xlsx', 'xls'])]),
        ),
    ]
