# Generated by Django 4.2.7 on 2024-01-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0016_alter_excelinput_excel_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instock',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Наименование'),
        ),
    ]
