# Generated by Django 4.2.7 on 2024-01-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0018_telegramidimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramidimage',
            name='id_image',
            field=models.CharField(unique=True, verbose_name='Id фото в телеге'),
        ),
    ]
