# Generated by Django 4.2.7 on 2024-01-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0019_alter_telegramidimage_id_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='instock',
            name='name_image_id',
            field=models.CharField(blank=True, editable=False, null=True, verbose_name='name image ID'),
        ),
        migrations.AddField(
            model_name='item',
            name='name_image_id',
            field=models.CharField(blank=True, editable=False, null=True, verbose_name='name image ID'),
        ),
        migrations.AddField(
            model_name='telegramidimage',
            name='name_image_id',
            field=models.CharField(default=None, unique=True, verbose_name='name image ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instock',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='telegramidimage',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Наименование'),
        ),
    ]
