# Generated by Django 4.2.7 on 2024-01-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0020_instock_name_image_id_item_name_image_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramidimage',
            name='name_image_id',
            field=models.CharField(null=True, verbose_name='name image ID'),
        ),
    ]
