# Generated by Django 4.2.7 on 2024-01-19 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0021_alter_telegramidimage_name_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramidimage',
            name='name_image_id',
            field=models.CharField(default=None, unique=True, verbose_name='name image ID'),
            preserve_default=False,
        ),
    ]
